name: SquareOne CI

on:
  push:
    branches:
      - feature/ghactions

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Show files
          run: |
            ls -la

      - name: Composer Install
        run: |
          printf '{ "github-oauth": { "github.com": "%s" } }\n' "${{ secrets.GH_CI_TOKEN }}" >> /root/.composer/auth.json
          echo COMPOSER_HOME
          composer install --ignore-platform-reqs --no-dev --optimize-autoloader
        env:
          WP_PLUGIN_ACF_KEY: ${{ secrets.WP_PLUGIN_ACF_KEY }}
          WP_PLUGIN_GF_KEY: ${{ secrets.WP_PLUGIN_GF_KEY }}

      - name: Yarn install
        run: |
          nvm use
          cp local-config-sample.json local-config.json
          yarn install

      - name: Gulp Build
        run: |
          npm install -g gulp-cli
          gulp dist
