name: SquareOne CI

on:
  push:
    branches:
      - feature/ghactions

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install
        run: |
          sudo bash dev/docker/global/start.sh
          sudo bash dev/docker/start.sh
          sudo sed -i '1s/^/nameserver 127.0.0.1\n/' /etc/resolv.conf